### ISSUE TITLE
Issue with uploading bam/sam files into IGV

### ISSUE THREAD

**Issue by alkartisan** [fuhuancheng/CRISPR-GRANT#1]
Hello!

I have successfully ran the program, but when I try to upload the Mapping_sorted.bam file into IGV, it asks for the index file ".bam.bai" file which is not there.  When I try the sam file instead, it asks me to correct the index and I'm not sure how that works (I do not have access to samtools).  I hoped to be able to just upload the .bam file into igv like the user guide for the software suggests, but I'm not sure what I am doing incorrectly.

Thanks,
Ashley

**Comment by hffqyd** [comment]
Sorry, but BAM indexing wasn't required in the current CRISPR indel analysis pipeline , so this step was excluded. If you can use a shell, the samtools has been already bundled in CRISPR-GRANT. Run the command in a shell, such as powershell in Windows, as below:

Open the samtools folder in the bin folder inside CRISPR-GRANT app directory, drag the samtools to the shell, and type ` index ` (there are blanks before and after `index`, then drag the bam file in the output to the shell, and then press the Enter key.

The whole command seems like this:

```
/some/path/to/samtools index /some/path/to/output-bam
```

Or, you can download the updated version, which I will upload to github release soon, which will add the bam index step. But with the new version, the whole analysis must be run again, sorry about this, so it's better to do the index only at this time, and use the new version next time.
